Имплементация типа Account, определение интерфейса IAccountRepository.
zykindmitry/charityCRM pull request #13
Opened 2019-11-22 08:50 UTC by afdenisoff-dev

Имплементация  вспомогательного типа Passord, определение интерфейса IPasswordConfig для работы с паролями.

2019-11-22 11:32 UTC, zykindmitry requested changes
Требуются доработки. IPasswordConfig - хорошее решение, за него плюс ))

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +                return ChangedAt != null
ChangedAt.HasValue вместо сравнение с null (работает несколько быстрее + принятый стандарт)

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +
Строки 205 - 209 это копипаста строк 193 - 197

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IAccountRepository.cs
> +    public interface IAccountRepository
У нас появился универсальный интерфейс IRepository<TEntity, TKey> необходимо наследоваться от него

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +                : new Password(Array.Empty<char>(), passwordConfig);
В реализации конструктора есть копипаста от которой можно избавиться например так:

public Account(...) : this(login, new Password(password ?? Array.Empty<char>(), passwordConfig))
{
}

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Я тут вижу усложнение типа Account. Гораздо проще, реализовать метод, который получает на вход пароль и сообщает о том совпадает он или не совпадает с тем что нам передали. с точки зрения аргументов могу выделить следующее:
1. Домен не должен зависеть от архитектуры вышележащих слоев (так мы повышаем связываемость системы и ухудшаем ее тестируемость и изменяемость)
2. Обращение к инфраструктуре (а обращение к репозиторию это потенциально работа с неуправляемыми ресурсами, сетевые запрос и т.п.) требует во-первых обработки исключительных ситуаций, во-вторых, подключения различных средств мониторинга (самое банальное измеряем время выполнения запроса и если оно превышает пороговое значение сигнализируем куда-то), логгирования и т.п.  Таким образом развивая в дальнейшем поддерживаемость и доступность системы мы будем усложнять код этого метода и увеличивая количество зависимостей доменного объекта. 
3. У нас возникает необходимость дополнительного действия, а именно построения неполного объекта типа Account, из другого объекта, содержащего логин и пароль (то что у нас пришло по Http или используется в форме), вместо этого мы можем сначала с помощью репозитория получить полноценный аккуант (если он не найден - сразу ошибка), если найден смотрим можно ли ему авторизоваться  с введенным паролем или нет, используя полученный из репозитория объект

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +            if (fromRepository == null)
Если такого аккаунта нет, то репозиторий вернет не null (мы как раз обсуждали неуместность null в данной ситуации, потому что непонятно null - потому что нет таких данных или null потому что ошибка в коде репозитория), а сгенерирует исключение

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Аналогичное замечание.

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +                ?? throw new ArgumentNullException(nameof(config), "Не инициализирована конфигурация параметров сложности пароля.");
Требуется перенос параметров конструктора ArgumentNullException (не влезает в экран интерфейса просмотра пулл реквестов)

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +                ?? throw new ArgumentNullException(nameof(config), "Не инициализирована конфигурация параметров сложности пароля.");
перенос

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// ВНИМАНИЕ!!! ИСПОЛЬЗУЕТСЯ ДЛЯ РЕГИСТРАЦИИ НОВОГО ПОЛЬЗОВАТЕЛЯ, ДЛЯ СБРОСА ПАРОЛЯ.
Для регистрации пользователя это мне понятно, для сброса пароля не очень. Я бы предложил для сброса пароля сделать метод Reset

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
Необходимо исправить повторы кода инициализации полей в различных конструкторах при помощи синтаксиса : this ( ... )

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            using (RNGCryptoServiceProvider crypto = new RNGCryptoServiceProvider())
var crypto = ... так как в данном случае тип переменной очевиден по правой части, а запись короче

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            Encoding utf8 = Encoding.UTF8;
var utf8 = ...

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            byte[] data = new byte[utf8.GetMaxByteCount(clearText.Length)
var data = ...

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            }
такой блок catch следует опустить, так как он ничего не меняет в данном случае.

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +                using (HashAlgorithm alg = new SHA512Managed())
var algorithm = ... (alg - избегаем аббревиатур в названиях переменных, кроме общепринятых) p.s. config можно отнести к общепринятым, встречал во многих популярных фреймворках

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            if (result.Length > 2)
Магическое число "2"

2019-11-22 11:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +                        if (((Password)password).RawHash[i] != RawHash[i])
Использование явного приведения типов загромождает код
можно проще:
var password = objectToCompare as Password;
if (password != null)
{
 ,,,
}

2019-11-23 10:45 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +            if (result.Length > 2)
У нас три флага - наличие цифр, спец. символы и верхний регистр. При длине пароля менее 3 символов одно из этих условий (если включены все три) всегда не выполняется. Конечно, такой сценарий маловероятен, но возможен. Поэтому проверка сложности начинается при длине пароля 3 и более символов.

2019-11-23 11:08 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// ВНИМАНИЕ!!! ИСПОЛЬЗУЕТСЯ ДЛЯ РЕГИСТРАЦИИ НОВОГО ПОЛЬЗОВАТЕЛЯ, ДЛЯ СБРОСА ПАРОЛЯ.
Сброс пароля = сброс значения ChangedAt в null + генерация + хеширование нового временного пароля, т.е. метод Reset будет повторять функционал конструктора. Вместо вызова Reset просто пересоздаем объект Account с помощью этого конструктора. Чем это плохо?

2019-11-23 11:50 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// ВНИМАНИЕ!!! ИСПОЛЬЗУЕТСЯ ДЛЯ РЕГИСТРАЦИИ НОВОГО ПОЛЬЗОВАТЕЛЯ, ДЛЯ СБРОСА ПАРОЛЯ.
Да. такой вариант вполне подойдет. Надо только не забывать про persistence: Старый объект пароль из хранилища не пропадет от того, что мы в Account поместим новый объект пароль. (В EF можно этого избежать если сделать Password структурой)

2019-11-24 03:26 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// ВНИМАНИЕ!!! ИСПОЛЬЗУЕТСЯ ДЛЯ РЕГИСТРАЦИИ НОВОГО ПОЛЬЗОВАТЕЛЯ, ДЛЯ СБРОСА ПАРОЛЯ.
Естественно, после сброса пароля надо новый временный пароль сохранить в хранилище. А что дает переделка Password в структуру?

2019-11-25 07:07 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Немного не понял. Нам для аутентификации требуется сравнить логины и пароли. С в вашем варианте не очень понятно, с чем сравнивать введенный логин и пароль. Пароль перед сравнением надо хешировать, но для этого нам нужна соль, которая хранится в репозитории. 
Я согласен с тем, что в домене в идеале не должно быть методов репозитория, но не понимаю, как без них обойтись. 
Мой алгоритм аутентификации: по логину получаем из репозитория аккаунт, если он получен - хешируем введенный пароль с солью из полученного аккаунта и сравниваем хеш введенного пароля и хеш из аккаунта. 
Ваш алгоритм аутентификации?

2019-11-25 07:36 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
К алгоритму аутентификации как таковой вопросов нет. Замечание касается того, что не все что делается при аутентикации должно делать в доменном объекте.
Предположим у нас есть контроллер, который получил POST-запрос на аутентикацию и вот как примерно должен выглядеть его код:

private readonly IAccountRepository repository;
public AuthResult Post(string login, string password)
{
    if (string.IsNullOrwhitespace(login)) { throw ... /* Бросаем HTTP Bad Request */  }
   
   var account = CallRepository(() => repository.FindByLogin(login)); /* В обощенный метод-расширения мы убрали try .. catch и обработку всех стандартных исключений, включая ObjectNotFoundException и бросит соотв. HTTP ошибку */
   string authenticationError;
   if (account.Authorize(password, out authenticationError)) { ... код в случае успеха ... }
  else {  ... код, возвращающий ошибку авторизации }   // некорректный логин или пароль, аккаунт заблокирован и т.п.
}

2019-11-25 07:38 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
В некоторых случаях между доменом и контроллером делают еще одну или две прослойки сервисов. Ода прослойка отвечает за некую транзакцию уровня домена, вторая за транзакцию уровня инфраструктуры. Контроллеру в этом случае остается только валидация входных данных, передача управления инфраструктурному сервису и возврат нужного результата в зависимости от того, что этот сервис вернет.

2019-11-25 07:47 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// ВНИМАНИЕ!!! ИСПОЛЬЗУЕТСЯ ДЛЯ РЕГИСТРАЦИИ НОВОГО ПОЛЬЗОВАТЕЛЯ, ДЛЯ СБРОСА ПАРОЛЯ.
EF мапит классы на таблицы, а структуры он мапит на колонки. Т.е. если у Вас есть class Account и в нем ссылка на класс Password с полями напр. Hash и ChangedAt, то это замапится на 2 таблицы Account и Password и в одной из них будет ссылка на другую (возможен любой вариант). Если Password будет структурой, то его свойства будут мапить не в отдельную таблицу, а добавляться к полям таблицы Account, в этом случае account.Password = new Password(...) и сохранение приведет к замещению значений в этих полях, соответственно старые значения из БД автоматически удалятся. В первом варианте старый объект Password придется удалять самостоятельно.

2019-11-25 07:59 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            if (result.Length > 2)
К этому вопросов нет, просто вместо "магических" чисел следует использовать именованные константы, например, не if (result.Length > 2), а if (result.Length > MinPasswordLength), где MinPasswordLength - константа объявленная внутри класса

2019-11-25 08:02 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            if (result.Length > 2)
После компиляции эта константа будет заменена на двойку обратно, т.е. никакой доп. нагрузки на компилятор во время выполнения не будет, зато код будет понятнее для другого разработчика. Так же не нужно заменять абсолютно все числовые константы на именованные константы. В ряде случаев (когда используется 0 или 1 или например берется остаток от деления на 2) это очевидно даже тому разработчику, который еще только разбирается в предметной области.

2019-11-25 08:51 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Спасибо, понял: объект аккаунт уже проинициализирован во внешнем коде. 
В нашем случае при аутентификации логин проверяется во внешнем коде, а в методе Authentiicate типа Account проверяем только введенный пароль.
Еще вопрос:
стоит ли оставлять отдельный метод авторизации? Я это сделал, исходя из того, что юзер может иметь аккаунт в системе, в которой может быть несколько сервисов, требующих отдельные разрешения на использование. Тогда тип аккаунт, по идее, должен иметь поле, содержащее перечень ролей в системе.  Кроме того, надо вводить какой-нибудь enums с ролями. Будем это делать?

2019-11-25 09:23 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Не только введенный пароль, но и состояние пароля и аккаунта.
Тип Role и Permission уже есть в системе, их связка с учетной записью предполагается, но не в рамках вашей задачи. Т.е. тип Account еще будет дорабатываться, рефакториться и все прочее.

2019-11-25 10:05 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Да, я увидел эти типы. Т.е. метод Authorize я оставляю NotImplementedException?

2019-11-25 10:25 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// ВНИМАНИЕ!!! ИСПОЛЬЗУЕТСЯ ДЛЯ РЕГИСТРАЦИИ НОВОГО ПОЛЬЗОВАТЕЛЯ, ДЛЯ СБРОСА ПАРОЛЯ.
Понятно. Тогда, если хранение аккаунта и пароля в разных таблицах БД необязательно,  лучше сделать Password структурой, как считаете?

2019-11-25 11:04 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Почему же, пароль-то мы можем сверить или при соответствии пароля вернуть ошибку о том, что пароль 100 лет не менялся и его пора сменить

2019-11-25 13:42 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Еще по классу Password вопрос остался:
если хранение аккаунта и пароля в разных таблицах БД необязательно, лучше сделать Password структурой, как считаете?

2019-11-26 05:15 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// ВНИМАНИЕ!!! ИСПОЛЬЗУЕТСЯ ДЛЯ РЕГИСТРАЦИИ НОВОГО ПОЛЬЗОВАТЕЛЯ, ДЛЯ СБРОСА ПАРОЛЯ.
Подумал, и решил все-таки сделать метод Reset, чтобы не заморачиваться с особенностями EF.

2019-11-26 08:09 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Да, со структурой будет проще

2019-11-26 08:18 UTC, zykindmitry requested changes

2019-11-26 08:18 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            }
весь блок можно упростить, используя Enumerable.SequenceEqual.

Т.е. вместо блока if ... else ... будет просто return Enumerable.SequenceEqual(RawHash, hashToCompare)

2019-11-26 08:18 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +                    hash = hashAlgorithm.ComputeHash(data, 0, RawSalt.Length + byteCount);
Есть отличия по стилю. using в 274 - 276 из одной строки содержит необязательные скобки, а этот using не содержит. Нужен какой-то единый стиль (вариант 274- 276 предпочтителен)

2019-11-26 08:18 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// <returns>Сгенерированный случайный пароль.</returns>
Анотация добавляется как правило к открытому члену. У закрытого члена ее никто не увидит.

2019-11-27 13:46 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Подумал, и решил все-таки сделать метод Reset, чтобы не заморачиваться с особенностями EF. Да и хранение паролей в отдельной таблице предпочтительней, нет?

2019-11-27 13:47 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Подумал, и решил все-таки сделать метод Reset, чтобы не заморачиваться с особенностями EF. Да и хранение паролей в отдельной таблице предпочтительней, нет?

2019-11-27 13:59 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
Повторы кода инициализации полей устранены.

2019-11-27 14:01 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// <returns>Сгенерированный случайный пароль.</returns>
Добавил аннотации к закрытым членам для облегчения изучения кода.

2019-11-28 07:27 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Account.cs
> +        }
Я думаю и так можно и так можно. Можно сделать выбор просто по вкусу.

2019-11-28 07:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            return returnResult;
Предалагаю небольшое сокращение: Убрать переменную returnResult, а вместо нее сделать return errorText.Any();

2019-11-28 07:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +        /// <returns>Сгенерированный случайный пароль.</returns>
Ок

2019-11-28 07:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
Повторы все же остались + появилось ветвление, которое в принципе можно избежать. 
Кроме того есть рекомендация по проектированию перегрузок как конструкторов так и методов - соблюдать одинаковую последовательность параметров (в сочетании с использованием интеллисенс в студии будет неудобно если ошибся в выборе перегрузки - примется уже напечатанные параметры переставлять)
Мой вариант:
public Password(IConfig config, byte[] salt, byte[] hash, DateTime? changedAt)
{
     Config = config ?? throw new ArgumentNullException(...);
     RawSalt = salt;
     RawHash = hash;
     ChangedAt = changedAt;
}

public Password(IConfig config) : this(config, null, null, null) // новый пароль
{
    Reset();
}

public Password(IConfig config, string salt, string hash, DateTime? changedAt) 
            : this(
                string.IsNullOrWhiteSpace(salt) ? Array.Empty<byte>() : Convert.FromBase64String(salt)
              , string.IsNullOrWhiteSpace(hash) ? Array.Empty<byte>() : Convert.FromBase64String(hash)
              , changedAt
              , config)

2019-11-28 07:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
Собственно вариант практически с Вашим совпадает, только нет повторов и if-ов

2019-11-28 11:15 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +            return returnResult;
Ок, только return **!**errorText.Any();
Если errorText содержит строки, то была ошибка валидации, надо возвращать false.,

2019-11-28 11:55 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
1. Про повторы: я понял так, что, в разных перегрузках конструктора не должно быть одинаковых строк инициализации полей, и устранил все копипасты. Вы указываете, что повторы остались. Поясните, пожалуйста, что Вы имеете в виду
2. В Вашем варианте вызов this(config, null, null, null)  -  неоднозначный для Password(IConfig config, string salt, string hash, DateTime? changedAt) и Password(IConfig config, byte[] salt, byte[] hash, DateTime? changedAt). Я поэтому и объединил конструкторы для нового пароля и пароля, введенного пользователем, чтобы избежать этой неоднозначности.

2019-11-28 11:58 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
P.S. Последовательность параметров исправлю, хотя поменял последовательность в основном конструкторе, чтобы выделить его. Так не принято?

2019-11-28 12:09 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
P.S. Последовательность параметров поправлю.

2019-11-29 06:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +            return returnResult;
Да

2019-11-29 07:07 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
1. 55 - 57 и 93-95 это не копипаста в полном смысле этого слова, но все же повтор. Если нам потребуется расширить тип Password новыми свойствами, то их инициализацию придется делать в 2 местах (и не забыть еще об этом). Это не великая проблема, но всегда лучше стремиться делать максимально просто, даже в мелочах. Потому что в большом проекте даже мелочи, накопившись в большом к-ве будут тормозить скорость разработки.
2. Да, это верно, без компилятора тут сложно заметить. Есть 3 варианта как это обойти:
    а) А зачем вообще нам третий конструктор. UI удобнее работать со вторым, EF параметры в конструктор 
         передавать не умеет. А раз нет сценария использования конструктора, то можно от него отказаться вовсе
    б) : this(config, string.Empty, string.Empty, null)
    в) : this(config, new byte[0], new byte[0], null)

2019-11-29 10:11 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
Предлагаю изменить набор конструкторов Password: 
1) public Password(IPasswordConfig config)
2) public Password(IPasswordConfig config, char[] clearText)
3) public Password(IPasswordConfig config, char[] clearText, byte[] salt) 
Эти три перегрузки - для работы с текстовыми паролями - генерация, смена, сравнение.
4) public Password(IPasswordConfig config, byte[] salt, byte[] hash, DateTime? changedAt) - это для получения данных из хранилища.

2019-11-29 10:16 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Password.cs
> +        }
При таком раскладе новые свойства инициализируем в конструкторе 3, но если их надо сохранить в хранилище, по-любому придется менять конструктор 4.

2019-11-29 10:29 UTC, zykindmitry approved these changes

2019-11-29 10:30 UTC, merged