Имплементация ICommand lдля создания, изменения, удаления и просмотра…
zykindmitry/charityCRM pull request #19
Opened 2019-12-15 10:18 UTC by afdenisoff-dev

… ролей.

2019-12-15 10:27 UTC, afdenisoff-dev commented
Есть один нюанс: при первичной загрузке данных в RoleRepository не подгружаются связанные Permissions. 
Если сделать ..Include(nameof(Role.Permissions)).Load(), то разрешения как бы подгружаются (коллекция Role.Permissions() содержит объекты по количеству привязанных ролей), но они равны null. 
Как я понимаю, не происходит маппинг данных на класс RolePermission.
Из-за этого get-role выдает исключение на списке привязанных разрешений.
Что с этим делать?

2019-12-15 13:34 UTC, zykindmitry requested changes

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/RoleRepository.cs
> +                .Load();
Не уверен, что разумно загружать все записи. когда требуется только одна.

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/RoleRepository.cs
> +                ?? throw new EntityNotFoundException(id, typeof(Role));
setOfRoles.Find(id) можно в одну строку, первый перенос по правилу приоритетов операторов идет на операторе ??

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/RoleAddPermissionCommand.cs
> +                if (role == null)
Если роли с таким roleId нет, то будет сгенерировано исключение. а не возврат null. Поскольку глобальная обработка исключений в консоли уже есть. то можно это все не проверять в команде

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/RoleAddPermissionCommand.cs
> +                if (permission == null)
метод GetById null не возвращает

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/RoleAddPermissionCommand.cs
> +                if (permission == null)
p.s. вероятно Вы не пробовали такой сценарий при отладке. Во многих командах, где руководство считает $$, от разработчика требуется, чтобы он проверял все разработанные им основные сценарии и альтернативные (т.е. 1 проверка на каждый сценарий + по 1 на каждый if). Советую сразу приучаться к систематизации процесса отладки кода, чтобы потом было легче.

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/RoleAddPermissionCommand.cs
> +                if (permission == null)
Чтобы было примерное понимание. Каждый пропущенный дефект, это до 1 часа работы тестера. т.е. оформление дефекта + его валидация после починки. Рейты тестера примерно в 2 раза меньше => все что укладывается в 30 минут проверки разработчиком - 100% стоит того. чтобы проверить

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/RoleDeleteCommand.cs
> +                if (role == null)
GetById не возвращает null

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/RoleDeletePermissionCommand.cs
> +                if (role == null)
см. выше

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/RoleDeletePermissionCommand.cs
> +                if (permission == null)
см. выше

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/RoleGetCommand.cs
> +            if (role == null)
тж.

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/RoleUpdateCommand.cs
> +                if (role == null)
тж

2019-12-15 13:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Role.cs
> +        }
Можно просто открыть Setter, а для целей валидации ввода см. решение для Permission.Name

2019-12-16 07:35 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Admin/RoleAddPermissionCommand.cs
> +                if (role == null)
Здесь и далее проверка на null делалась, когда PermissionRepository.GetById имел первую реализацию, возвращающую null. Потом реализация изменилась, а проверку на null я не убрал из PermissionCommand, а потом, не глядя, скопировал в RoleCommand. Конечно, надо было проверять.

2019-12-16 07:37 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Admin/RoleAddPermissionCommand.cs
> +                if (permission == null)
Сценарий-то я пробовал, видел исключение, но, про ненужную проверку на null не вспомнил...

2019-12-16 10:59 UTC, zykindmitry submitted a review, later dismissed

2019-12-16 11:00 UTC, zykindmitry approved these changes

2019-12-16 11:00 UTC, merged