Issue-20: Имплементация CashDonation, CommodityDonation, EF Core конф…
zykindmitry/charityCRM pull request #21
Opened 2019-12-17 09:45 UTC by afdenisoff-dev

…игурации

2019-12-17 14:58 UTC, zykindmitry requested changes

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Ioc/ServiceCollectionExtension.cs
> +                .WithRepository<ICommodityDonationRepository>();
Репозитории по условиям задачи не требовались, но раз уж сделали, то давайте попробуем оставить только 1 репозиторий, но скажем с обощенным методом, позволяющим получить пожертвования только определенного типа

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/CashDonationRepository.cs
> +                ?? throw new EntityNotFoundException(id, typeof(CashDonation));
Find(id) можно не переносить dbSet.Find(id) вполне удовлетворяет требованию максимальной длины строки в 100 символов

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Ioc/ServiceCollectionExtension.cs
> +                .WithRepository<ICommodityDonationRepository>();
Попробуйте так же теперь замапить CashDonation и CommodityDonation в одну таблицу используя шаблон Table Per Hierarchy (а не Table Per Concrete Type, который был реализован). В перспективе возможно этот вариант будет полезнее.

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Donation.cs
> +    public class Donation : IAmPersistent<int>
На перспективу int-а может не хватить. Пожертвования бывают и по 10 рублей.

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Donation.cs
> +    public class Donation : IAmPersistent<int>
Хотя конечно через нашу систему придется прогнать несколько десятков миллиардов рублей, чтобы int переполнился ...

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Donation.cs
> +        }
Возникает вопрос. Если я при помощт этого конструктора создам var donation = new Donation(), то я смогу его сохранить в хранилище ? Если не смогу, то может мне не стоит его создавать вовсе ? А если мне не стоит его создавать, может и возможности мне такой не давать

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Donation.cs
> +        public string Description { get; set; }
Обычно описание пожертвования содержит текст, указанный жертвователем и менять его на стороне благотворительной организации нельзя.

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CommodityDonation.cs
> +        public static string CommoditiesFieldName => nameof(commodities);
Недавно выяснил, что у ef core есть баг и такой подход для navigation не работает. То, что сработало у Вас есть следствие того, что ef core нашел свойство по наименованию (оно у Вас совпадает с именем свойства с точностью до регистра), а так же того ,что в конфигурации было указано PropertyAccessMode = Field. Т.о. этот статик к сожалению бесполезен.

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CommodityDonation.cs
> +        }
Эта реализация полностью повторяет базовую

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CommodityDonation.cs
> +        }
Если Commodity и Cash будут лежать в одной таблице, то эта перегрузка не потребуется

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Donation.cs
> +        }
При хранении в Cash и Commodity в разных таблицах такая перегрузка будет необходима в обоих классах, а в этом классе она использоваться никогда не будет

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CommodityDonation.cs
> +            : this()
: base(description)

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CommodityDonation.cs
> +        protected CommodityDonation() // для ORM
: base() // вдруг в базовом появятся коллекции, которые инициализируются в этом конструкторе

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Commodity.cs
> +        public uint Quantity { get; }
uint не является CLR совместимым типом. Т.е. не факт, что используя сборки, написанные не на c#, смогут с этим типом работать. Лучше uint не использовать в интерфейсах модулей.

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Commodity.cs
> +                && (commodity.Id == Id && commodity.Quantity == Quantity && commodity.Cost == Cost);
Достаточно сравнить идентификатор. Либо если Вы пытаетесь решить задачу сравнения разных версий одного и того же пожертвования, то придется взять хэш-код и от Description-а. Но в хранилище данных может быть только 1 объект с одним id.

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Commodity.cs
> +        public CommodityDonation CommodityDonation { get; set; }
1) Иметь и навигационное свойство и внешний ключ это нехорошая практика, тк позволяет сконструировать объект, где CommodityDonationId = 10 , а CommodityDonation.Id того же объекта - 15
2) Имень двусторонние навигационные свойства с родителя на детей и с детей на родителя, по тем же причинам. Полученные объекты можно привести в противоречивое состояние и везде в коде это придется перепроверять ,а так же при создании этих объектов не забывать все это заполнять

Нужно устранить дублирование, оставив навигацию только там, где это реально нужно. А нужна она только в CommodityDonation. Так как Commodity вне пожертвования нам не нужны.

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Commodity.cs
> +        public CommodityDonation CommodityDonation { get; set; }
Второй момент, у нас нет возможности переносить предметы с одного пожертвования на другое. В реальной жизни такие вещи если  иделают, то через механизм корректировки, чтобы было видно, что пожертвование не подделано фондом, а перенаправлено на другие нужды.
Потому и открытый setter излишен

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Commodity.cs
> +        public Commodity(string description, uint quantity, Nullable<double> cost = null)
Commodity без Donation не существует, поэтому необходимо передавать ссылку на пожертвование в конструктор

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Commodity.cs
> +        public Commodity(string description, uint quantity, Nullable<double> cost = null)
Необходимо использовать краткую форму double? вместо Nullable<double> для сокращения кода

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CashDonation.cs
> +        public double Amount { get; }
Деньги хранят в сберкассе ))) а сберкасса хранит их в decimal ,а не в double. Так как double - вещественное с плавающей точкой по основанию 2, а decimal - 10. С double может быть такая штука, Вы ввели 9,5, а по факту сохранилось что-то типа 9,4999

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Commodity.cs
> +        public Nullable<double> Cost { get; }
decimal?

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CashDonation.cs
> +        }
Достаточно Id

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CashDonation.cs
> +        }
тж что и в commditydonation:
1) если оба типа в одной таблице ,то перегрузка не нужна вовсе
2) если мы сравниваем разные версии одного пожертвования (хотя пожертвование это по природе иммутабельный объект, не может фонд там ничего менять), то надо учитывать все поля ,включая и текстовые, либо только Id

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CashDonation.cs
> +            Description = description;
Дублирует код базового конструктора

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/CommodityConfiguration.cs
> +        {
commodity.ToTable(...)

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/CommodityConfiguration.cs
> +                .Property(x => x.Quantity);
короткие строки все же не стоит переносить. увеличение к-ва строк метода, тоже не способствует его читаемости. перенос строк мы все же рассматриваем как вынужденную меру, а не как необходимую

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/CashDonationConfiguration.cs
> +                .IsRequired(false);
Вот тут сразу заметен недостаток Table per Concrete Type. Поле объявлено в базовом классе, а сконфигурить его можно по-разному в разных таблицах.  (впрочем у Table Per Hierarchy тоже есть недостатки)

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/CommodityDonationConfiguration.cs
> +            commodityNavigation.SetField(CommodityDonation.CommoditiesFieldName);
последний вызов лишний (см. коммент ниже)

2019-12-17 14:58 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/CommodityDonationConfiguration.cs
> +                .WithOne();
+ задать имя внешнему ключу ,а то ef core сгенерил CommodityDonationId1 в качестве имени

2019-12-25 07:30 UTC, zykindmitry requested changes

2019-12-25 07:30 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/DonationRepository.cs
> +            }
Валидация объектов лежит на самих объектах (иначе зачем нам ООП). Репозиторий может проверять такие вещи как уникальность.
Т.е. тип CachDonation либо должен гарантировать то, что Amount строго больше нуля (что вполне реально в данном случае), либо иметь признак IsValid, а репозиторий в свою очередь смотрит на этот признак и бросает исключение если он false.
Так же это позволит отказаться от двух интерфейсов ICachDonation, ICommodityDonations и иметь 1 интерфейс и одну реализацию Create, Delete и т.п.

2019-12-25 07:30 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/DonationRepository.cs
> +            }
Ну и стиль текста об ошибке. В крупных системах желательно использовать деловой стиль, а не разговорный )))

2019-12-25 07:30 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CashDonation.cs
> +            Amount = amount;
Вот тут как раз можно и бросить исключение если сумма оказалась меньше либо равной нулю

2019-12-25 07:30 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/CashDonation.cs
> +        // Т.к. CommodityDonation и CashDonation хранятся в одной таблице, то не перегружаем Equals и GetHashCode
и убираем регион...

2019-12-25 07:30 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Commodity.cs
> +        public CommodityDonation CommodityDonation { get; }
Перекрестная ссылка осталась

2019-12-25 07:30 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Donation.cs
> +        }
Конструктор необходимо сделать protected. Так как воспользоватьс яэтим конструктором откуда-либо кроме потомков не получится (класс абстрактный)

2019-12-26 08:59 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/DonationRepository.cs
> +            }
Если делать один интерфейс IDonationRepository, то мы не сможем наследовать его от IRepository, т.к. в этом случае надо указывать конкретный тип, а у нас их два.
Значит, создаем IDonationRepository<TEntity, long> без наследования от IRepository, 
Насколько это правильно, ведь тогда цепочка наследования не сохраняется? 
Или я что-то не так понимаю, тогда поправьте.

2019-12-26 09:01 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/DonationRepository.cs
> +            }
Про стиль - долго ковырялся с репозиториями и конфигурациями миграций, решил расслабиться )

2019-12-26 11:27 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/DonationRepository.cs
> +            }
Тип действительно один - Donation. IDonationRepository : IRepository<Donation, long>

2019-12-27 07:58 UTC, zykindmitry approved these changes

2019-12-27 07:58 UTC, merged