Добавлена поддержка команды crate-fund_registration (FundRegistration…
zykindmitry/charityCRM pull request #22
Opened 2019-12-26 04:44 UTC by nrdnfella

…CreateCommand)

2019-12-26 07:12 UTC, zykindmitry submitted a review, later dismissed

2019-12-27 08:05 UTC, zykindmitry requested changes

2019-12-27 08:05 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Admin/FundRegistrationUpdateCommand.cs
> +                //fundRegistration.Name = parameters[1]; //не удается присвоить имя, т.к. свойство Name класса FundRegistration недоступно вне класса.
Тогда надо убрать параметр

2019-12-27 08:05 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/FundRegistrationConfiguration.cs
> +            fundRegistration.Property(x => x.Description).IsRequired();
Если я не ошибаюсь, то Description не является обяательным для доменного объекта

2019-12-27 08:05 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/FundRegistrationConfiguration.cs
> +            fundRegistration.Property(x => x.Name).IsRequired().HasMaxLength(100);
см. класс RealString и его использование. Если мы не позволяем хранить объекты с именами длиннее 100 символов, то это истоничк потенциальных ошибок. Если мы к примеру реализуем репозиторий, сохраняющий данные локально, а потом синхронизующий их с сервером, то мы позволим данные сохранить, а потом ен сможем синхронизировать. Ограничения доменного объекта должны быть строже либо идентичны ограничениям хранилища.

2019-12-27 08:12 UTC, nrdnfella commented on DevFactoryZ.CharityCRM.UI.Admin/FundRegistrationUpdateCommand.cs
> +                //fundRegistration.Name = parameters[1]; //не удается присвоить имя, т.к. свойство Name класса FundRegistration недоступно вне класса.
то есть изменить можно только описание? если название, то создавать новую заявку?

2019-12-29 07:48 UTC, zykindmitry submitted a review, later dismissed

2019-12-29 08:03 UTC, zykindmitry approved these changes

2019-12-29 08:04 UTC, merged