Реализован синхронный js-сценарий аутентификации с использованием Xml…
zykindmitry/charityCRM pull request #39
Opened 2020-03-25 14:32 UTC by afdenisoff-dev

…HttpRequest.

Исправлена ошибка, приводившая к созданию лишних Guid для пользовательских сессий.

2020-03-26 06:00 UTC, zykindmitry requested changes

2020-03-26 06:00 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/login.js
> +        else {
Это событие срабатывает на каждую смену статуса. в т.ч. и в сам момент отправки. Поэтому при асинхронной отправке будет сначала 2 алерта : запрос не выполнен, а потом уже алерт с результатом запроса.

2020-03-26 06:00 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/login.html
> +                    <button type="submit" class="btn btn-primary btn-lg btn-block" onclick="login()">Войти</button>
Причина неработающего асинхронного запроса не в том, что у вас тут кросс-сайт запрос (которого кстати говоря и нет. запрос идет на тот же домен, с которого и был скачан html. Кросс-сайт предполагает другой домен, т.е. другой адрес до первого / в адресе ресурса.

Причина в специфическом Html элементе: <button type="submit" ... (см. в лекции по HTML раздел формы) предназначен для отправки POST запросов. Когда на такую кнопку нажимают, то выполняются сценарии соответствующих событий, а затем идет повторная загрузка страницы (была бы кнопка внутри тэга form с указание адреса, то ушел бы POST запрос на нее).
Если вы отправляете запрос синхронно, то он держит выполнение сценариев и перезагрузка происходит после того, как запрос выполнен. Если вы отправляете запрос асинхронно, то страница перегружается после отправки запроса и ответ на запрос уже никто не ждет.

Чтобы это поведение изменить нужно сделать "магию" onclick="login(); return false;", этот false интерпретируется браузером как неуспешная валидация формы и перезагрузка не происходит.

2020-03-26 06:01 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/login.js
> +    }
Отсутствует ; (на "умный" java script компилятор браузера полагаться не стоит, иногда он не умеет правильно расставлять ; сам, тем более что есть случаи когда невозможно однозначно решить нужна ; или нет)

2020-03-26 06:03 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/login.js
> +        if (this.readyState == this.DONE) {
=== вместо == (== всегда более тяжелая операция, так как приводит правую часть к типу левой части. Лучше привыкать использовать ===, а == использовать именно там, где мы предполагаем преобразование типов)

2020-03-27 05:27 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/login.html
> +                    <button type="submit" class="btn btn-primary btn-lg btn-block" onclick="login()">Войти</button>
Да, здесь нет кросс-сайта. Это я при отладке экспериментировал, запускал сервер и логин на разных адресах.
Вопрос: мне оставить синхронную реализацию, или все-таки делать асинхронную?

2020-03-27 05:38 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/login.html
> +                    <button type="submit" class="btn btn-primary btn-lg btn-block" onclick="login()">Войти</button>
Если коротко, то делать асинхронную. Если подробнее, то на практике синхронные ajax запросы практически не используются. Ни для публичных приложений, ни для корпоративных, так как это блокирует интерфейс на неопределенное время (сетевые тормоза человечество пока не победило).

2020-03-27 06:17 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/login.html
> +                    <button type="submit" class="btn btn-primary btn-lg btn-block" onclick="login()">Войти</button>
Ок. Как лучше оформить проверку readyState? Названия статусов в объекте XmlHttpRequest в разных браузерах могут меняться. Сравнивать с числами?

2020-03-27 06:28 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/login.html
> +                    <button type="submit" class="btn btn-primary btn-lg btn-block" onclick="login()">Войти</button>
Нет необходимости в этом. Для запросов мы будем использовать Fetch API, там это все разруливается. А сейчас заморачиваться не стоит

2020-03-30 11:07 UTC, zykindmitry approved these changes

2020-03-30 11:08 UTC, merged