Реализация login.html средствами React и Fetch API
zykindmitry/charityCRM pull request #41
Opened 2020-04-06 11:47 UTC by afdenisoff-dev

2020-04-06 13:39 UTC, zykindmitry requested changes

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/base.jsx
> +}
Рассмотрим вопрос о необходимости этих компонентов против использования непосредственно input в jsx.
"плюсы": нет, так как они ничего не реализуют ничего нового по сравнению с обычным input
"минусы": анализируемость (чем больше файлов / компонент / кода и его вложенность Component A ссылается на Component B и т.п., тем сложнее разобраться в коде), повторное использование (повторное использование этих компонент вынуждает нас задавать все возможные атрибуты элементов даже если нас в конкретном месте устраивают их значения по умолчанию, напр. autocomplete)... т.о. мы пишем больше лишнего кода. что опять же снова бьет по анализируемости. 
Итого при не столь значительных минусах. они все же перевешивают плюсы.

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/loginForm.jsx
> +};
Можно повторить анализ необходимости этого компонента по аналогии с предыдущим и мы опять получим некоторые незначительные минусы при отсутствии плюсов.

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/loginForm.jsx
> +        );
предлагаю закрывающую скобку писать либо на последней строке (даст краткость записи, допустимо все элементы не имеющие смысловой нагрузки закинуть в конец последней строки statement-а) либо на одном уровне с а) открывающей скобкой б) всего statement-а. Как решите. так и будем дальше придерживаться

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/loginForm.jsx
> +);
Этот код я бы предложил поместить на самой странице в тэге scripts либо вынести в отдельный Javascript файл. В противном случае разработчик. который захочет разобраться в том, что монтируется на странице будет вынужден просмотреть все подключенные javascript файлы в поисках таких вот выражений. Тут либо мы размещаем это на самой странице либо предлагаем стандарт, зная который разработчик раз узнав этот стандарт. сможет быстро разбираться с другими страницами.

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/loginForm.jsx
> +﻿function LoginComponent(props) {
Слово Component в названии избыточно. Для JSX достаточно того, что элемент называется в Pascal стиле. чтобы отличать React-компоненты от обычных тэгов, разумно и нам использовать тот же критерий.

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/loginForm.jsx
> +            <a href="react.html">
На странице авторизации не следует упоминать адресов других ресурсов. которые есть в приложении. Это облегчает жизнь злоумышленникам. а пользователям никак не помогает (пока он не ввел пароль он никуда попасть не может). Если нужна фэйковая ссылка. можно указать href="#"

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/loginForm.jsx
> +            <ButtonComponent type="submit" cssClass="btn btn-primary btn-lg btn-block" onClick={login} caption="Войти"/>
login - должен быть либо методом компонента-класса (предпочтительно), либо получать обработчик в качестве props иначе мы получаем лишнюю зависимость между компонентами приложения (любая зависимость. которой можно избежать является "лишней").

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/login.js
> +        //httpPostByXMLHttpRequest(loginURL, user);
Можно проанализировать полезность этой строки кода ))))
плюсы: отсутствуют (коментарий не несет полезной информации для других разработчиков)
минусы: анализируемость (ну в общем логика примерно такая же как выше)

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/login.js
>          alert("Не указано имя пользователя или пароль.");
В перспективе тут будет не alert. а вывод в DOM текста ошибки (типа валидаторов), при реализации это потребует вызвать setState у компонента Login. потому эта функция потенциально должна быть методом самого компонента

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/login.js
> +function httpPostByXMLHttpRequest(url, data) {
Неиспользуемая функция

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/login.js
> +async function httpPostByFetch(url, data) {
Поскольку мы не планируем отправлять запросы несколькими средствами. то уточнять это в имени метода не имеет смысла. 
А вот вынести этот код в некий базовый js было бы неплохо. У нас content-type всегда будет JSON и не хотелось бы этого повторять на каждой странице.

2020-04-06 13:39 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/login.html
> +    <script src="js/components/loginForm.jsx"></script>
Необходимо использовать модули (см. конец второй лекции по javascript)

2020-04-12 05:52 UTC, zykindmitry requested changes
Что касается валидации. В нашем шаблоне есть html/css отображения ошибок ввода (см. https://colorlib.com/polygon/concept/pages/form-elements.html скролить вниз до текста Validation States. В том случае когда мы не хотим / не можем сказать, какое именно поле ввода содержит неверные данные  (при авториации если пользователь ввел корректные логин и пароль, но такого сочетания логин / пароль мы не нашли, то мы не сообщаем что именно неправильно) мы подсвечиваем таким образом все поля.

P.S. И вот сочетание <input type="text: ... > вместе с необходимой обвязкой для отображения Validation State уже вполне тянет на самостоятельный компонент, повторное использование которого дает другим разработчикам реальный выигрыш по времени.

2020-04-12 05:52 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/base.js
> +        alert(`${response.status}: ${response.statusText}. ${result}.`);
Реакция на ответ должна быть в вызывающем коде. Обычно в js это делают через передачу функций-коллбэков.
function A() { ... } function B(x, y, onSuccess, onError) { ... onSuccess(r); ... } ... B(x, y, A);

2020-04-12 05:52 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/base.js
> +        alert(`Запрос завершился с ошибкой: [${e.name}]${e.message}.`);
В fetch api обработку исключений реализуют следующим образом:

fetch(url).then((response) => {
  if (response.ok) {
    return response.json();
  } else {
    throw new Error('Something went wrong');
  }
})
.then((responseJson) => {
  // Do something with the response
})
.catch((error) => {
  // exception handler
});

2020-04-22 06:03 UTC, zykindmitry requested changes
2 замечания осталось

2020-04-22 06:03 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/loginForm.jsx
> +};
У нас есть уверенность, что нам где-то понадобится такой же HTML, но с другими headerImageCss или headerImageSrc ?

2020-04-23 06:28 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/loginForm.jsx
> +};
Этот принцип мне понятен, и в целом я с ним согласен. Но  все люди разные, в т.ч. с разной квалификацией. Из-за этого взгляд на архитектуру и компоновку может быть разный. Я в обсуждаемом задании подошел к решению, исходя из  того, что, в общем случае, любая web-страница может содержать хидер, футер и боди. Соответственно сделал компоненты. Это во-первых. Во-вторых, мне это было полезно, чтобы лучше разобраться с темой. Ок, я объединю все в один компонент.

2020-04-23 07:04 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/wwwroot/js/components/loginForm.jsx
> +};
"взгляд на компоновку может быть разный" - если в контексте квалификации, то да. В вопросах архитектуры безусловно есть "вкусовщина", но все же ключевые моменты должны определяться не вкусом и привычкой, а быть обоснованы обстоятельствами. которые формируют требования к архитектурному решению.

2020-04-27 10:26 UTC, zykindmitry approved these changes

2020-04-27 10:26 UTC, merged