Features/isuue 33
zykindmitry/charityCRM pull request #42
Opened 2020-05-07 06:59 UTC by afdenisoff-dev

Промежуточная фиксация.  Реализация backend, админки, REST API.

2020-05-08 07:33 UTC, zykindmitry requested changes

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/CharityDbContext.cs
> +            return GetRepository<TEntity, TKey>()?.GetById(id) ?? Find<TEntity>(id);
Какова цель этого изменения?

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardAddressConfiguration.cs
> +                address.Property(p => p.Flat);
Мы вроде бы решили сделать два поля адрес и город

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardCategorySubCategoryConfiguration.cs
> +    internal class WardCategorySubCategoryConfiguration : IEntityTypeConfiguration<WardCategory.WardCategorySubCategory>
Для чего введен тип SubCategory ?

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardConfiguration.cs
> +                .HasKey(x => x.Id);
Перенос избыточен. Строка не достаточно длинная (замечание относится и к другим переносам - не повторяю)

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Services/WardService.cs
> +        public Ward Create(WardData data)
При создании тоже будут добавляться категории. разумно это предусмотреть

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/Api/WardsController.cs
> +        public ActionResult<WardListViewModel[]> Get()
Потребуется фильтр по ID категории

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/Api/ViewModels/WardViewModel.cs
> +        public IEnumerable<WardCategory> WardCategories { get; set; }
не уверен, что при POST / PUT запросах эта коллекция заполнится

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/Api/WardsController.cs
> +                service => service.Update(id, viewModel.ToDto()));
Update и Create должны делать и Grant / Deny

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +        public Address() //For ORM
достаточно protected

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +            , string flat)
Правила переноса: перенос после запятой, а не перед

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +        public string Flat { get; private set; }
Точно EF удается заполнить значение при чтении из БД несмотря на private модификатор?

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardAddressConfiguration.cs
> +                address.Property(p => p.Street);
По умолчанию поле будет VARCHAR(MAX), необходимо задавать максимальную длину. а в домене использовать тип RealString

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +            Flat = newAddress.Flat;
Проще будет открыть поля на set и не делать лишних методов. Кроме того. если есть необходимость изменить только 1 поле, то придется вычитывать и заполнять все остальные чтобы не затереть

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FullName.cs
> +            SurName = newFullName.SurName;
Т.ж. не вижу необходимости в таком методе

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FullName.cs
> +            return base.GetHashCode();
Такая реализация GetHashCode не согласуется с реализацией Equals. Для двух Equals объектов хэш-код будет разный

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/IAddress.cs
> +        void Update(IAddress newAddress);
сеттеры вместо update

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/IFullName.cs
> +        void Update(IFullName newFullName);
сеттеры вместо update

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Ward.cs
> +        public static int PhoneMaxLength = 12;
Маловато для телефонного номера
+7 (nnnn) nn-nn-nn
или предполагается хранение только цифр ?

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Ward.cs
> +        public class ThisWardCategory
ThisWardCategory - название не отражает назначение класса. Варианты: WardToWardCategory WardCategoryCollection и т.д. WardCategoryOfWard

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Ward.cs
> +                return WardCategoryId;
WardCategoryId.GetHashCode()
хэш-функция должна быть необратимой функцией, т.е. по ее значению не должно быть возможно восстановление аргумента

2020-05-08 07:33 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Ward.cs
> +        public void Grant(WardCategory wardCategory)
Grant / Deny все-таки терминология из области прав на доступ. Тут более уместны AssignCategory, UnassignCategory или банальные AddCategory / RemoveCategory тоже подойдут. Главное добавить что именно мы добавляем

2020-05-11 07:15 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/CharityDbContext.cs
> +            return GetRepository<TEntity, TKey>()?.GetById(id) ?? Find<TEntity>(id);
Я столкнулся с тем, что, когда я использую в консольных командах сервис unitofwork  для работы с хранилищем, то при вызове GetById отрабатывает метод сервиса, без загрузки связанных сущностей.  Метод же конкретного репозитория настроен для загрузки всего, что необходимо. Вот, собственно, поэтому.

2020-05-11 07:19 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardAddressConfiguration.cs
> +                address.Property(p => p.Flat);
Я, когда начал делать, решил, что лучше сразу сделать более  структурированно, чем просто произвольная строка.

2020-05-11 07:20 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardCategorySubCategoryConfiguration.cs
> +    internal class WardCategorySubCategoryConfiguration : IEntityTypeConfiguration<WardCategory.WardCategorySubCategory>
Для того же, что и ThisWardCategory - реализация отношения многие-ко-многим между категориями.

2020-05-11 07:25 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardConfiguration.cs
> +                .HasKey(x => x.Id);
Ок, но для меня чисто визуально удобнее выглядит, когда Linq-методы вынесены на отдельные строки. Более читабельно. То же касается и запятой, разделяющей параметры метода, когда параметры вынесены в отдельные строки.  Запятая перед параметром для меня более наглядна.

2020-05-11 07:28 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Services/WardService.cs
> +        public Ward Create(WardData data)
Включить Ienumerable<WardCategory> в WardData или добавить параметр в конструктор?

2020-05-11 07:30 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/CharityDbContext.cs
> +            return GetRepository<TEntity, TKey>()?.GetById(id) ?? Find<TEntity>(id);
Если в сборке есть тип репозитория для данной сущности, то использовать его.

2020-05-11 07:57 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Web/Api/ViewModels/WardViewModel.cs
> +        public IEnumerable<WardCategory> WardCategories { get; set; }
Эта коллекция заполняется при GetById для показа в UI. Если веб-форма редактирования подопечного будет позволять изменять его категории, то и для POST\PUT коллекция будет использоваться. Или я не так понял замечание?

2020-05-11 08:01 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Address .cs
> +            , string flat)
Ответил выше. Это принципиально?

2020-05-11 08:03 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Web/Api/WardsController.cs
> +                service => service.Update(id, viewModel.ToDto()));
А разве viewModel  уже не приходит к нам с коллекцией категорий?

2020-05-11 08:07 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Address .cs
> +        public string Flat { get; private set; }
У меня при тестировании заполняет - API возвращает адрес

2020-05-11 08:33 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Address .cs
> +            Flat = newAddress.Flat;
Здесь я сомневался, как лучше сделать - методом или открыть сеттеры.  Пока решил сделать так, и обсудить это  с Вами.

2020-05-11 08:34 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FullName.cs
> +            return base.GetHashCode();
Это ошибка, исправлю

2020-05-11 08:37 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Ward.cs
> +        public static int PhoneMaxLength = 12;
Да, предполагается хранить только цифры. Включая код страны.

2020-05-11 08:42 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Ward.cs
> +        public class ThisWardCategory
С названием да, не все в порядке. Все какие-то корявые получались. Ок, остановимся на  WardCategoryCollection

2020-05-11 08:45 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Ward.cs
> +                return WardCategoryId;
Вводим множитель - простое число?

2020-05-11 08:51 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Ward.cs
> +        public void Grant(WardCategory wardCategory)
Да, с названиями я тоже долго определялся. Решил сделать так и обсудить с Вами. Плодить множество вариантов для методов, выполняющих, с технической точки зрения, одинаковые операции, тоже как-то не очень. Хотя, с предметной точки зрения, функционал вроде бы и разный.

2020-05-12 05:41 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardAddressConfiguration.cs
> +                address.Property(p => p.Flat);
Пользователь планирует скопипастить адрес одной строкой в одно поле. Чтобы такая структура работала придется реализовать парсинг и валидацию по КЛАДРу.

2020-05-12 05:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardCategorySubCategoryConfiguration.cs
> +    internal class WardCategorySubCategoryConfiguration : IEntityTypeConfiguration<WardCategory.WardCategorySubCategory>
Связь между категориями не многие ко многим, а 0..1 to many. Т.е. у одного элемента может быть только 1 родитель. а не много.

2020-05-12 05:50 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardConfiguration.cs
> +                .HasKey(x => x.Id);
Оформление кода должно быть единым во всем проекте. Каким именно. не столь важно. Правила. конечно, можно поменять, но это приведет к необходимости переформатировать уже наработанную базу кода. что представляется весьма трудоемким. С точки зрения обучения полезно отвязаться от личных привычек в оформлении если такие привычки сформировались. Будет печально если из-за разногласия в таких мелочах с будущим лидом не заладятся отношения (а такое бывает, к сожалению, не все лиды достаточно мудры ...)

P.S. К примеру я не люблю правило именование полей с символа подчеркивания, в своих проектах никогда его не использую, но на моем проекте в компании Kaspersky это принято как проектное правило именования полей и я использую именно его. В других компаниях / проектах были другие стандарты. Не могу сказать, что это обстоятельство вызывает у меня какие-то затруднения.

2020-05-12 05:59 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/Api/ViewModels/WardViewModel.cs
> +        public IEnumerable<WardCategory> WardCategories { get; set; }
А вы это проверяли. Я имею ввиду, что если Вы запостите на API JSON объект с массивом WardCtegories, то будет ли заполняться эта коллекция при десериализации. В данном случае замечание относится именно к функциональной стороне - "работает ли это?"

2020-05-12 06:05 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +            , string flat)
Ответил на ответ выше. Принципиально не положение запятой как таковое. а единство в стиле оформления. В реальном проекте с десяток разработчиков и каждому удобно по-своему, если каждый будет оформлять код так, как ему удобно, то единого стиля не будет. Это в свою очередь затрудняет анализ кода. Затрудняет не существенно? - да, но ведь и придерживаться единого стиля совсем не сложно. А бывают и такие случае, когда некоторых разработчиков отсутствие единого стиля раздражает => зачем давать повода ищущим повода. пусть лучше эффективно работают. а поводы побухтеть ищут в других местах (это уже просто из опыта).

2020-05-12 06:06 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +            Flat = newAddress.Flat;
Давайте обсудим. Какие Вы видите плюсы / минусы того и другого вариантов ?

2020-05-12 06:08 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Ward.cs
> +        public class ThisWardCategory
WardCategoryCollectionItem или Element так пожалуй будет точнее

2020-05-12 06:10 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Ward.cs
> +                return WardCategoryId;
Можно просто WardCategoryId.GetHashCode() если Вы не планируете сохранять это значение где-либо и потом пользоваться как хеш-функцией, то этого вполне достаточно. Т.к. равенство результатов базового GetHashCode не гарантируются на разных серверах.

2020-05-12 06:12 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Ward.cs
> +        public void Grant(WardCategory wardCategory)
Для типов домена предпочтительнее отражать именно предметную сторону, а не техническую. Техническую сторону, если нужно. как правило можно поместить в комментарии.

2020-05-12 10:17 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardAddressConfiguration.cs
> +                address.Property(p => p.Flat);
Это одно из функ. требований - возможность вставки строки с адресом? А если не давать пользователю возможности копипастить?  Распарсить все, что может прийти в голову пользователю, невозможно (у. или ул., пр. или пр-т, г. или гор. , с точкой или без), да и последовательность в строке может быть разной (в Новосибирске, по-моему, есть Красный проспект - написать можно по-разному). 
Предлагаемый вариант, конечно, половинчатый. С одной стороны, пользователь потратит на 1 мин. больше, вводя данные в отдельные поля, при этом может тоже всякую фигню написать. С другой стороны, не надо сейчас городить валидацию, прикручивать КЛАДР. Можно сделать это потом., если понадобится.

2020-05-12 10:33 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardCategorySubCategoryConfiguration.cs
> +    internal class WardCategorySubCategoryConfiguration : IEntityTypeConfiguration<WardCategory.WardCategorySubCategory>
Значит, я неправильно понял Ваше уточнение про категории в комментах к задаче:  "Каждая категория может иметь сколько угодно дочерних категорий и т.п." - я это понял как многие-ко-многим. 
Если переделывать на 0...1 -ко-многим, то надо будет делать проверку на наличие родителя.
Так что, переделываем?

2020-05-12 10:55 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardConfiguration.cs
> +                .HasKey(x => x.Id);
Для меня следовать правилам также несложно. Еще раз уточним: пишем без переноса, если оператор до 100 символов. Если больше - переносим. Вопросы по правилам переноса: 
1.  Переносим только то, что за сотым символом, или начинаем раньше (например, с первого параметра метода, и все остальные параметры - в отдельной строке)?
2. Если string больше 100 символов, используем StringBuilder?

2020-05-12 10:58 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Web/Api/ViewModels/WardViewModel.cs
> +        public IEnumerable<WardCategory> WardCategories { get; set; }
Это не проверял. Проверю.

2020-05-12 12:19 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Address .cs
> +            Flat = newAddress.Flat;
Вариант с методом:
+ уменьшает вероятность забыть изменить или, наоборот, случайно переписать свойство.  
+ упрощает внедрение нового функционала, связанного с доп. обработкой или валидацией входных данных.
- требует создания объекта адреса для передачи методу. Но гуру дотнета твердят, что CLR  создает объекты быстро, поэтому не надо этого бояться.
- нет возможности отдельно изменить одно свойство
Вариант с сеттерами зеркален - все минусы первого - это плюсы второго, плюсы первого - минусы второго.

Но в текущей реализации при вводе адреса в админке есть недоработки: 
1. Не отслеживается случай, когда требуется обнулить какое-то свойство. (записать пустую строку) 
2. Нельзя отдельно изменить один компонент адреса - если компонент отсутствует в строке команды, то он обнуляется.
У меня есть вариант, который проще реализовать, если использовать метод Update:
в ком. строке указываются только изменяемые компоненты. Для остальных соответствующие свойства аргумента метода Update получают значение null. В методе происходит соответствующая проверка: если null, то остается текущее значение компонента адреса. 
Если требуется обнулить компонент, то в ком. строке для него не указывается новое значение. Тогда в аргументе для Update соответствующее свойство получает значение string.empty, которое затем и присваивается компоненту адреса.  
Ваше мнение?

2020-05-12 13:15 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardAddressConfiguration.cs
> +                address.Property(p => p.Flat);
Тут видимо нужно прояснить задачу и область применения КЛАДР. Задача ввода и хранения адреса в нашей системе состоит в том, что один сотрудник заводит информацию о подопечном и вводит адрес, а другой использует этот адрес для оказания адресной помощи (отправка почтовых отправлений, визит). Когда и для каких задач используют КЛАДР: когда есть 2 или более информационные системы, между которыми есть обмен данными, содержащими в числе прочего адреса, кроме того адрес как минимум в одной из систем используется в качестве классификатора. Т.е. для одной из систем не допустимо, чтобы 1 абонент имел улицу "красный проспект", а другой "пр-кт Красный", потому что эти абоненты будут отнесены к разным улицам, а это в свою очередь повлечет за собой ошибки в учете. не сойдутся какие-нибудь отчеты и т.п.

Если у вас такая задача. то вы можете легко на пальцах показать пользователю, какие проблемы он получит если не согласится потратить доп. время на ввод адреса в разные поля с проверкой по соответствующим справочникам. И когда пользователь сравнит эти проблемы он вполне может согласиться на КЛАДР. Если же отсутствие КЛАДРа никаких ощутимых проблем ему не создаст, то он их не "купит".

 В нашей системе в качестве классификатора может выступать только город проживания. так как отчет об оказании помощи в разрезе города обязательно потребуется, потому и было предложение разделить адрес на город и все остальное

Что касается вопроса "что если потом к системе предъявят требования, для которых потребуется применение КЛАДРа. а у нас будет куча данных без КЛАДРа ?" Тут как мы уже говорили действует старое доброе правило: "не решаем гипотетических проблем"

2020-05-12 13:26 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardCategorySubCategoryConfiguration.cs
> +    internal class WardCategorySubCategoryConfiguration : IEntityTypeConfiguration<WardCategory.WardCategorySubCategory>
Да. при выполнении запроса чтения списка придется отфильтровать категории. выбрав только руты. а у них в свою очередь загрузить коллекцию детей, при том что в самом объекте WardCategory нет информации о том является ли он рутом или нет.

2020-05-12 13:29 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.Persistence.EFCore/Configuration/WardConfiguration.cs
> +                .HasKey(x => x.Id);
1. Нет. Строка длиной более 100 символов целиком разбивается по правилам переноса
2. StringBuilder это уже не совсем к оформлению кода. Скажем так включать StringBuilder только ради того, чтобы сделать выражение разбиваемым на несколько строк для соблюдения правил переноса - не нужно. (помним кстати. что в .NET сложение двух константных строк после компиляции сразу будет преобразовано в константу. т.е. в рантайм никакого сложения уже не будет).

Т.о. если строка длиной более 100 символов не может быть разбита на строки (вообще либо правила переноса не делают ее всю или какую-то часть короче 100 символов), то перенос не выполняем.

2020-05-13 06:02 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +            Flat = newAddress.Flat;
"уменьшает вероятность забыть изменить или, наоборот, случайно переписать свойство." - не уверен, разработчик с тем же успехом может забыть заполнить соответствующее свойство при создании объекта-параметра.
"упрощает внедрение нового функционала, связанного с доп. обработкой или валидацией входных данных" - это плюс, но сама по себе доработка относится к разряду "гипотетических" => мы не можем брать ее во внимание. (все то же правило не обслуживаем гипотетических доработок). Ведь точно так же можно придумать возможных доработок, где альтернативный вариант удобнее. Что же касается changability, то здесь уместно говорить о количестве зависимостей между типами например или количеством функций того или иного компонента (в контексте единственная / множественная ответственность). Эти критерии более универсальны. Если мы хотим выбрать из двух вариантов такой. который будет в дальнейшем легче изменяться. то надо смотреть именно на них. Рассматривать же гипотетические изменения, то тут слишком много разных вариантов, которые придется проанализировать.

2020-05-13 06:10 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +            Flat = newAddress.Flat;
-- первый минус: да это минус (причем речь не только о времени работы, но и потребления памяти), но как вы верно заметили совсем несущественный, в частности он никак не влияет на попадание нами в нефункциональные требования по быстродействию и / или ресурсопотреблению => можно принимать во внимание только при прочих равных (хотя нередко бывают именно такие ситуации. когда между вариантами решения отличия именно такого рода).
второй минус: нет возможности отдельно изменить свойство, это недостаток из категории reusability, тоже не очень страшный, но все же

Есть еще один минус: кода больше. это уже недостаток из категории анализируемость

2020-05-13 06:18 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +            Flat = newAddress.Flat;
Что касается варианта с null. Да. вариант вцелом рабочий, использование null таким образом допустимо. так как отсутствие данных и есть единственно верная интерпретация null. Однако надо опять же сравнить плюсы и минусы. В вашем варианте устраняется минус номер 2 и частично минус номер 3, который я указал. 

Если "положить на весы", что у нас получается. Получается, что мы ради удобства реализации определенной доработки. которая не факт, что когда-либо состоится, заранее пишем некоторый дополнительный код (а каждый лишний стейтмент, это время на анализ + место для ошибки). Очень между прочим распространенная ошибка. У меня помнится один разработчик написал серверный asp.net mvc грид на задачу отображения списка с данными (причем это был прототип). На вопрос зачем. ответил, а вдруг мы захотим добавлять колонки, менять типы данных, мое решение удобнее. просто в источник данных поле добавь и все )) Это пример такой же ошибки, только гораздо более гипетртрофированный

2020-05-13 06:18 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +            Flat = newAddress.Flat;
P.S. Так мы там вроде оставляем всего два поля

2020-05-13 06:23 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Address .cs
> +            Flat = newAddress.Flat;
P.P.S. Получил обратную связь от пользователя. что ввод адреса отдельно улицу, дом и т.п. их устраивает. И проверить этот адрес тоже вполне актуально. так как часто ошибаются. Им главное, чтобы адрес целиком можно было скопировать

2020-05-15 07:36 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Web/Api/ViewModels/WardViewModel.cs
> +        public IEnumerable<WardCategory> WardCategories { get; set; }
Проверил. Коллекция заполняется.

2020-05-17 06:42 UTC, zykindmitry requested changes

2020-05-17 06:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/Api/WardCategoriesController.cs
> +        }
Этот метод нам потребуется для просмотра справочника категорий. А вот для отображения дерева категорий до 2-го уровня нам нужна коллекция только рутовых категорий. Т.о. тут нужен параметр, что-то вроде bool root, где false (он же default ) означает, что нужны все категории, а true - только рутовые

2020-05-17 06:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Ward.cs
> +                        nameof(wardCategory));
А нам действительно нужно запрещать добавлять вновь созданную категорию ?
+ Я бы в этот конструктор добавил wardid, раз уж мы его тоже прикапываем

2020-05-17 06:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Ward.cs
> +            WardCategories.Remove(new WardCategoryCollectionElement(wardCategory));
По идее мы должны найти уже существующий объект. обнулить у него WardId и затем уже удалить иначе мы получим неконсистентный объект

2020-05-17 06:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/Filters/CategoryFilterAttribute.cs
> +        private class CategoryFilter : Stream
Обычно потомка типа Stream называют BlaBlaBlaStream (аналогично XXXException, SomeAttribute и т.п.) В данном случае CategoryFilteredStream

2020-05-17 06:42 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/Filters/CategoryFilterAttribute.cs
> +                            new CategoryFilter(context.HttpContext.Response.Body, categoryIds);
Это не работает потому, что Body нельзя заменить объектом типа Stream. Body это объект типа Microsoft.AspNetCore.Server.IIS.Core.HttpResponseStream (см. https://github.com/dotnet/aspnetcore/blob/master/src/Servers/IIS/IIS/src/Core/HttpResponseStream.cs )
Вполне возможно, что с объектами другого типа asp.net core просто не работает, возможно просто интерфейса типа Stream не достаточно (из-за отсутствия методов BeginWrite и др.).
Обычно свойство Body не инициализируются другим объектом, а используют HttpContext.Response.Write(...)

2020-05-18 05:58 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Web/Api/WardCategoriesController.cs
> +        }
Какие категории считаем рутовыми? Вопрос возник потому , что  в текущей реализации возможна ситуация, когда иерархия категорий "закольцована": cat1->cat2->...->catN->cat1. Проверяется только наличие циклической ссылки между двумя "соседними" категориями.
Итак, рутовые - это те, которые не имеют родителей, т.е. не входят в список подкатегорий любой другой категории?

2020-05-18 06:09 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM.UI.Web/Api/WardsController.cs
> +        public ActionResult<WardListViewModel[]> Get()
Да, в следующем коммите будет правильный фильтр. через параметр int? categoryId. Но мне бы хотелось понять, как работает класс CategoryFilterAtribute. Ниже я изложу то, что понял и чего не понял.

2020-05-18 15:12 UTC, zykindmitry commented on DevFactoryZ.CharityCRM.UI.Web/Api/WardCategoriesController.cs
> +        }
1. Рутовые, это те, у которых ParentId в БД равен NULL
2. Пока не нужно

2020-06-09 06:18 UTC, zykindmitry approved these changes

2020-06-09 06:18 UTC, merged