Первая пробная фиксация
zykindmitry/charityCRM pull request #7
Opened 2019-11-01 09:27 UTC by afdenisoff-dev

Описание членов класса FundRegistration - в summary.
В определении интерфейса IFundRegistrationRepository использованы стандартные CRUD-названия методов.

2019-11-01 13:19 UTC, zykindmitry requested changes
Требуется внести изменения и дать пояснения по ряду вопросов

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        #region .ctor and properties
Группировка членов типа (если она необходима) осуществляется по функциональному признаку. Т.е. не регион "свойства",  "методы", "события" и т.п., а регионы "создание объекта" (или .ctor), "валидация", "ссылка для подтверждения" и т.п. (это я указывал в readme, но возможно было не очень понятно). Идея простая, удобно группировать код таким образом, чтобы вызываемые друг другом члены были ближе.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +    public class FundRegistration
Я бы предложил снабдить комментарием и сам класс. Объяснить его назначение, так как он будет многократно использоваться.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        public FundRegistration(string name, string description, TimeSpan linkMaxLifeTime)
Комментарий к самому конструктору (достаточно формального "создает экземпляр типа FundRegistration).
Тут важно дать описание параметров, особенно последнего.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        /// Краткое описание. Может быть пустым. Передается в конструкторе класса.
Возникают вопросы. Краткое описание чего, кто его пишет и для кого оно предназначено в рамках процесса регистрации фонда. То что он инициализируется в конструкторе класса не совсем соответствует действительности, так как он может задаваться и при помощи открытого set.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        string RegistrationLink
Аннотация к свойству конечно помогает разобраться, но все же может ввести в заблуждение разработчика, который будет использовать этот тип. У меня к примеру первая мысль, что тут лежит вся ссылка целиком.
Могу предложить переименовать свойство, а в анотации подробнее написать какая именно часть ссылки тут лежит, а именно идентификатор ссылки. И раз уж речь зашла об идентификаторах, то строка не самый удачный тип данных для идентифтикатора из-за затратности сортировки / вычисления хэш функции и т.п., тогда как Guid это 128-битный идентифтикатор

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Можно воспользоваться упрощенным синтаксисом:

public string Name { get; } (и в конструкторе Name = name)

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
упрощенный синтаксис 
public string Description { get; set; }

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Упрощенный синтаксис  (см. выше)

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Необходио единообразие. Либо мы обособляем код внутри региона пустыми строками сверху и снизу, либо нет.
Что выберете, так и будем дальше использовать в качестве стандарта.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Если я обращусь к getter-у RegistrationLink до того, как вызову этот метод, не заметив что этот метод есть, я получу null. Таким образом Вы позволяете объекту этого типа находиться в неконсистентном состоянии. Есть 2 варианта (которые вижу я, можете предложить что-то свое):
1) сделать метод приватным и вызывать его в случае если обратились к геттеру, а link еще null (т.е. отложеная инициализация)
2) в геттере бросать исключение (если линк еще null). Для этого стандартно используют System.InvalidOperationException. А в тексте сообщения укажите ,что разработчику сделать ,чтобы он этого сообщения не получал. Правда я лично прибегаю ко второму пути если первы йне реализуем или а) CreateRegistrationLink делает что-то потенциально long running или задействует unmanaged ресурсы. Т.е. следуя правилу не делать на get / set неожиданно длительных или ресурсоемких действий с побочными эффектами

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
еще 3 вариант вижу. Можно это все сделать в конструкторе. Зачем нам заставлять разработчка писать еще 1 строчку кода, так как сценарий создания экземпляр Вашего класса без создания ссылки (если только это не восстановление из хранилища данных, но об этом сейчас не заморачиваемся)

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        /// <param name="link">Переменная часть ссылки на регистрационную форму.</param>
поясните для чего нам возвращать link. По идее процесс такой. Пользователь зашел на URL, определенный обработчик получил управление и значение линк получил в качестве параметра. Нашел по нему наш объект и спросил у него можно отдавать данные или нельзя.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +using System.Text;
Лишние юзинги стоит удалять. В данном случае это 2 последних если не ошибаюсь.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +using System.Text;
т.ж. лишние using-и

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +}
1. Нужны аннотации на интерфейсе и каждом методе (в большинстве случаев разработчик будет иметь дело с репозиториями, приведенными к интерфейсу, т.е. IDE будет брать аннотацию из него)
2. Интерфейсные методы обособляем пустой строкой сверху и снизу, чтобы улучшить читаемость

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        int Create(FundRegistration entity);
что возвращает int ? (собственно была бы аннотация, было бы понятно)

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        FundRegistration Read<TKey>(TKey key);
Не совсем понятно (видимо из-за отсутствия аннотации) для чего тут параметр-тип. У FundRegistration могут быть несколько ключей разного типа ?

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        bool Update(FundRegistration entity);
1. вопрос к возвращаемому результату
2. в современных ORM реализован шаблон Unit of work. Для изменения состояния достаточно изменить объект и затем вызвать один общий save. Так что мтеод Update не нужен.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        void Delete(FundRegistration entity);
для удаления вполне достаточно и ключа, не обязательно передавать весь объект (т.к. прежде его придется получить методом Read)

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        IEnumerable<FundRegistration> FindBy(Func<FundRegistration, bool> predicate);
А нам точно нужен универсальный поиск. Как я понимаю у нас следующие сценарии:
1) может потребоваться список всех заявок (для админа, чтобы посмотреть и удалить ошибочно созданную)
2) может потребоваться поиск по линк

Тут дело в чем, если Вы объявляете универсальный метод, то должны его реализовать. Да не просто реализовать, а чтобы он гарантировал свою работу для тех параметров, которые принимает (включая производительность, ресурсы и т.п.) либо бросал исключение с понятным описанием проблемы.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        public FundRegistration(string name, string description, TimeSpan linkMaxLifeTime)
Такая реализация конструктора позволяет мне создавать заявки с null в качестве имени фонда.

2019-11-01 13:19 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        #endregion
Что мне мешает дважды зарегистрировать фонд по одной заявке ? Не достает признака (а лучше даты), того, что по данной заявке фонд уже зарегистрирован.

2019-11-02 04:40 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        #region .ctor and properties
Да, я не посмотрел версию readme от 28.10.2019. Делал по аналогии с тестовыми задачами. Исправлю.

2019-11-02 04:40 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +    public class FundRegistration
Комменты добавлю.

2019-11-02 04:41 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        public FundRegistration(string name, string description, TimeSpan linkMaxLifeTime)
Комменты добавлю.

2019-11-02 04:48 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        /// Краткое описание. Может быть пустым. Передается в конструкторе класса.
Комменты исправлю и добавлю.

2019-11-02 04:56 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        string RegistrationLink
У меня была мысль сделать тип GUID, но меня смутила жесткая привязка к этому типу, т.к. раньше я не пользовался им для создания уникальных идентификаторов. Если это - обычная практика, то, конечно, надо делать тип GUID.

2019-11-02 04:59 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Ок. Это я для первого раза все расписывал как в букваре.

2019-11-02 05:02 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
обособляем.

2019-11-02 05:16 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Пойдем по варианту 1, т.к. неуправляемые ресурсы не используем и потенциальных побочных эффектов нет (если только тип GUID при генерации значения не лезет куда-нибудь в Win-api)

2019-11-03 06:15 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Ок

2019-11-03 06:15 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Ок

2019-11-03 06:22 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +using System.Text;
ок

2019-11-03 06:22 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +using System.Text;
Ок

2019-11-03 06:22 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +}
Ок

2019-11-03 06:24 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        int Create(FundRegistration entity);
int возвращает primary key созданного в хранилище объекта.

2019-11-03 06:27 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        FundRegistration Read<TKey>(TKey key);
Сделал так, поскольку мне неизвестна модель данных в хранилище.

2019-11-03 06:33 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        bool Update(FundRegistration entity);
1. Возвращает флаг успешности/неуспешности операции обновления данных в хранилище.
2. В общем случае разработчику, вроде бы, не должны быть известны возможности используемой ORM, и вызывать метод Save где-то надо, нет? А этот интерфейс ,как я понял, абстрагирует ядро решения от ORM. Или я что-то не так понял?

2019-11-03 06:36 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        void Delete(FundRegistration entity);
А если объект в хранилище был изменен кем-то и разъехался с тем, что было в локальном репозитории?

2019-11-03 06:39 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        IEnumerable<FundRegistration> FindBy(Func<FundRegistration, bool> predicate);
Хм, в описании issue про реализацию интерфейса не было ))) (шутка).
Конечно, я понимаю, что его надо реализовать. Я немного работал с EF, и делал подобную реализацию. Правда, на больших данных ее не тестировал.

2019-11-03 06:42 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        public FundRegistration(string name, string description, TimeSpan linkMaxLifeTime)
Можно же валидировать UI-форму и уже там не пропускать empty\null. 
Но если нужна проверки и здесь, то как ее лучше сделать? Бросать исключение?

2019-11-03 06:48 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        bool Update(FundRegistration entity);
Пояснение к п.2: я имел в виду, что со стороны ядра разработчик не должен лезть в ORM, для этого есть данный интерфейс, А при реализации интерфейса под конкретную ORM уже использовать ее возможности.

2019-11-03 06:50 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        #endregion
Согласен, не этот вариант не продумал.  Подумаю, как это сделать.

2019-11-03 07:36 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        #endregion
" зарегистрировать фонд" - это значит создать форму для регистрации, на которую ссылается ссылка, отправляемая админом инициатору создания фонда?

2019-11-03 09:30 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Guid.NewGuid() - для генерации guid вызывает COM-функцию Win-API. Это является потенциальным источником побочных эффектов? На всякий случай сделаю по варианту 2.

2019-11-03 09:38 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
не обособляем.

2019-11-03 09:53 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Guid.NewGuid() - для генерации guid вызывает COM-функцию Win-API. Поэтому, наверное, вариант 2 лучше не использовать.  Но из хранилища мы тоже получать будем, почему не учесть это сразу?

2019-11-03 09:55 UTC, afdenisoff-dev commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        }
Guid.NewGuid() - для генерации guid вызывает COM-функцию Win-API. Поэтому, наверное, вариант 1 лучше не использовать. Но из хранилища мы тоже получать будем, почему не учесть это сразу? Т.е. сделать открытым сеттер?

2019-11-05 08:07 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        bool Update(FundRegistration entity);
Тут не Ваша ошибка. Логика Ваша мне понятна. Просто если делать insert / update / delete для каждой сущности в отдельности это будет потенциально неэффективно, особенно если требуется транзакционность. Поэтому мы, делая insert / delete, и изменяя состояние объектов, сагруженных из источника данных накапливаем изменения. А потом единожды открыв соединение и стартовав транзацию заливаем их в БД.

2019-11-05 08:18 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        string RegistrationLink
Да, эта привязка не является критичной. Вероятность, что пользователя не устроит формат ссылки, которая ему приходит или нефункциональные требования так поменяются, что GUID перестанет нас удовлетворять довольно низкие.

2019-11-05 08:20 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        bool Update(FundRegistration entity);
По поводу флага. В случае неуспеха сохранение бросается исключение. Это исключение будет "поднято", до точки входа и затем пишется в лог. Если Вы будете логгировать ошибки отдельно в слое DAL, а вызывающему коду просто сообщать "что-то пошло не так", то Вы получаете 2 потенциальные проблемы:
1. В логе не будет всего стека вызова и Вы, пытаясь воспроизвести ошибку, может не понимать что за сценарий к этой ошибке привел (если репозиторий используется более чем в одном пользовательском сценарии)
2. Некоторые ошибки, возникающие при попытке сохранить изменения, могут быть связаны с действием пользователя. Например нарушен какой-нибудь уникальный индекс. В этом случае надо уведомить пользователя о том, что фонд с таким названием в системе уже есть (к примеру), вариант "что-то пошло не так" будет некорректен в таком случае.

2019-11-05 08:22 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        void Delete(FundRegistration entity);
Вы вероятно имеете ввиду оптимистичную блокировку. Поскольку мы имеем дело с объектами, которые будут создаваться редко и только администратором, то необходимости в реализации блокировки не вижу.

2019-11-05 08:32 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        IEnumerable<FundRegistration> FindBy(Func<FundRegistration, bool> predicate);
Совсем от EF абстрагироваться конечно не получится ... но все же. Следует исходить из практической необходимости. Кроме того параметр должен быть Expression<Func<...>> иначе он не может быть транслирован в SQL запрос. Кроме того, в Expression<Func> не засунуть постраничный вывод, сортировку и т.п. Выходит придется либо делать суперуниверсальный метод Файнд, который принимает IQueryable<T>. И вот тут мы уже получим серьезные ограничения с выбором альтернативных хранилищ данных.

2019-11-05 08:37 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        public FundRegistration(string name, string description, TimeSpan linkMaxLifeTime)
Валидировать UI-форму нужно. Но доменный объект в общем случае конструируется не только с UI. Есть еще импорт / экспорт ну и восстановление состояния из БД. В конкретном случае полезность этой проверки невысока, так что на Ваше усмотрение.

2019-11-05 08:40 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        #endregion
"зарегистрировать фонд" это значит пройти по ссылке и заполнить некоторые данные. в результате создастся фонд в системе после чего ссылка должна стать недоступной ,чтобы исключить попытку повторной регистрации по ошибке либо третьими лицами

2019-11-06 04:41 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        void Delete(FundRegistration entity);
Вспомнил о том, что EF все равно нужна загрузка объекта, просто не обязательно в этот процесс вовлекать backend. Тут вопрос удобства. Мне в контроллер придет id объекта, который надо удалить и в 1 строчку кода передам этот id для удаления записи.

2019-11-10 05:27 UTC, zykindmitry requested changes
Три ключевых замечания: а) по id (которого у нас нет) б) по дате регистрации, которая нигде не задается в) по одной из проверок валидности, которая делает объект невалидным всегда
Плюс пару замечаний по стилю: а) именование свойств, хранящих дату некоторого события б) обособление строк кода пустыми строками

P.S. Рекомендация по описанию классов и их членов. Лично я сторонник объемных и исчерпывающих описаний / комментариев, но современный разработчик, воспитанный на соц. сетях их не читает потому что "многобукв". Поэтому боюсь Ваш труд будет пропадать напрасно ))) Современному разработчику нужно кратко и только самую суть.

2019-11-10 05:27 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        FundRegistration GetById(int id);
В этой сущности нет id. Роль первичного ключа выполняет Guid

2019-11-10 05:27 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/Persistence/IFundRegistrationRepository.cs
> +        void Delete(int id);
В сущности нет ключа типа System.Int32

2019-11-10 05:27 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +            if (DateOfRegistration < DateTime.UtcNow && DateOfRegistration > DateTime.MinValue)
Это условие делает ссылку невалидной всегда. Дата регистрации всегда будет меньше текущей даты и времени и всегда больше минимального значения DateTime

2019-11-10 05:27 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +            return true;
Код if (smth) return X; return Y; следует упрощать, используя in-line синтаксис return smth ? X : Y;

2019-11-10 05:27 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +        public DateTime DateOfRegistration { get; }
1) Принцип именования идентификаторов свойств хранящих дату и время какого-то события следует именовать по одинаковым принципам (единообразно):
DateOfRegistration, RegistrationLinkGUIDCreatedTimeUTC на первый взгляд кажется, что это одно и тоже (если судить только по названиям). Есть несколько вариантов выбора стиля для именования полей типа дата, который мне встречался:
 - (Самый короткий) CreatedAt (ведь это дата создание нашего объекта, вместе с GUID-ом, а то что это время UTC, можно указать в комментарии), RegisteredAt (я бы назвал ClosedAt или SucceededAt, потому что зарегистрировался фонд, т.е. другая сущность, а зявка на регистрацию стала выполненой или закрытой)
 - DateOfRegistration (или DateOfClosure), DateOfCreation
 - RegistrationDate, CreationDate
2) Пока ссылка не была использована для регистрации, то значение этого свойства должно быть null. Для value-типов (к которым относится и System.DateTime) существует обобщенный reference-тип Nullable<T>. Который может быть кратко записан как T?, т.е. в данном случае DateTime?
3) Данное значение нигде не задается. т.е. всегда будет заполнено нулями в памяти

2019-11-10 05:27 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/FundRegistration.cs
> +            RegistrationLinkGUIDCreatedTimeUTC = DateTime.UtcNow;
Я бы предложил пустыми строками обособлять только какие-то "блоки" кода. Обособление каждой строки отнимает слишком много экранного места (т.к. бывают конструкторы и "по-больше")

2019-11-11 04:37 UTC, zykindmitry approved these changes
Небольшие стилистические шороховатости подправлю сам, с точки зрения проектирования типа все норм. Единственный момент Create-e нет смысла возвращать Guid, тк он уже есть в объекте, а в случае с ключами, генерируемыми на стороне БД, то они будут генерироваться в момент Save, а не в момент Create

2019-11-11 04:37 UTC, merged