Features/issue 6
zykindmitry/charityCRM pull request #9
Opened 2019-11-11 19:58 UTC by nrdnfella

2019-11-12 04:34 UTC, zykindmitry requested changes
Созданный тип WardCategory действительно реализует модель иерархического справочника. С функциональностью все ОК. Реализованный тип модели называется "анемичная модель". У нее есть свои преимущества (например производительность), но повышение maintainability системы не из их числа. Нам в данном случае важнее именно модифицируемость => нас интересует парадигма ООП. Что здесь можно улучшить в рамках ООП:
1. ParentId 
Представим, что у нас есть 2 объекта типа WardCategory (catA (c Id = 1), catB (с Id = 2)). Если мы запишем catA.ParentId = 2; catB.ParentId = 1; а затем попробуем построить дерево, то мы получим StackOverflowExeption. Т.е. наш тип должен нас защищать от "зацикливания". 
Как это сделать:вместо int ParentId. делаем например IEnumerable<WardCategory> Children { get; }
и методы AddChild(WardCategory) RemoveChild(WardCategory) и в методе AddChild мы проверим, что ни сама категория. ни один из ее Child-ов не совпадает с нашим объектом.

2. Id - это идентификатор категории, в т.ч. и в хранилище данных. Что будет если мы изменим его значение (данный тип это позволяет) ? - он останется без своих подкатегорий, а при созранении в БД будет ошибка связанная с внешним ключем. => Id не должен быть изменяемым извне.

3. Name - Категория должна обладать непустым именем. иначе в дереве она будет выглядеть как пустое пространство. Сейчас тип это позволяет. я могу создать объект типа WardCategory и не инициализировать свойство Name. т.о. сделать его "безымянным". Решением данной проблемы будет требование передавать name в конструктор типа и в конструкторе дополнительно проверять . что имя задано корректно при помощи статического метода string.IsNullOrWhiteSpace (см. пример в классе FundRegistration. Александр уже делал подобную валидацию). Кроме того set свойства Name должен содержать такую же проверку (т.е. упрощенный синтаксис свойства нас тут не устроит. придется руками делать поле string name, в Name get { return name }, а в set проверять value тем же образом. что и name в конструкторе.

+ пара мелких стилистических замечаний

2019-11-12 04:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +    class WardCategory
Класс не будет доступен вне сборки.

2019-11-12 04:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +    /// Категория подопечного благотворительного фонда
Предлагаю использовать аббревиатуру БФ = благотворительный фонд. я ее уже использовал в других классах т.к. встречаться будет часто

2019-11-12 04:34 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +        //Идентификатор категории
Лучше использовать стандартный комментарий. тогда он будет использоваться (по аналогии с описанием класса)

2019-11-12 04:36 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +        public int ID { get; set; }
По соглашению о едином стиле. для идентификаторов свойств мы используем стиль Pascal, т.е. каждое отдельное слово в идентификаторе начинается с заглавной, а остальные литеры маленькие (ID -> Id)

2019-11-12 21:53 UTC, nrdnfella commented
Дмитрий, внес изменения в класс категории подопечных БФ.

2019-11-12 21:53 UTC, closed without merging

2019-11-13 09:16 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +        #endregion
В других классах мы договорились делать отступ в 1 строку от # region / #endregion

2019-11-13 09:16 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +                    "не может быть пустым.");
Перенос не по  соглашению переноса + морфологическая ошибка в тексте 
throw new ArgumentException(
    nameof(name),
    "Название категории подопечного не может быть пустым" (уточнение про БФ можно опустить, других подопечных в системе не будет)

2019-11-13 09:16 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +        private string name;
Описание закрытых членов не требуется. В отдельных случаях если считаете, что наименования поля недостаточно для понимания его назначения можно добавлять стандартный комментарий // ... А xml-нотация актуальная только для открытых членов

2019-11-13 09:16 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +                        "не может быть пустым.");
перенос (см. в конструкторе) + морфологическая ошибка в тексте категории подопечнОГО

2019-11-13 09:16 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +        private bool IsCategoryEqualsAnyOfItsChildren(WardCategory wardCategory)
Имя метода не соответствует правила английского языка.
1) category is black, но category equals to ... соответственно в вопросительной форме DoesCategoryEqual
2) ну и предлог to пропущен

Могу предложить вариант по-короче: делаем метод IsChild и вызываем не this.IsCategoryEquals... (category), а наоборот category.IsChild(this)

2019-11-13 09:16 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +        public Guid Id { get; private set; }
Guid в данном случае не является удачным типом для идентификатора. Чем Guid хуже int-а?
1. Если Guid генерируется не на стороне БД, то мы не можем быть уверены в его уникальности => есть риск ошибки при работе пользователя
2. Вставки записей с ПК типа Guid (особенно массовые при импорте / экпорте) более ресурсоемкие, за счет более длительной процедуры построения индекса

=> чтобы выбрать именно Guid нужны какие причины в противовес. Для сущности FundRegistration этим противовесом служит необходимость доступа по сгенерированной ссылке неавторизованному пользователю. Если использовать int, то такие ссылки будут легко брутфорситься (т.е. злоумышленник будет ходить по ссылкам https://<some url>/1,  https://<some url>/2, https://<some url>/3 и т.д. и искать "живые ссылки". При этом сущность FundRegistration создается 1 на фонд и создается админом

2019-11-13 09:16 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +                wardCategory.Parent = this;
Коллекция чайлд категорий в итоге остается пустой. Как правило при проектировании стараются избегать перекрестных ссылок и прибегают к ним только тогда, когда по-другому никак. Так ка кэто потенциальный источник рассинхронизации данных (что мы и получили в данном случае) и усложняет восстановление состояния из БД.  Т.е. либо все "дети" имеют ссылку на "родителя", а "родители" не имеют коолекции детей ,либо наоборот "дети" не имеют ссылку на "родителя", а "родитель" имеет коллекцию "детей". Выбор обычно в пользу второго варианта, так как с ним проще на UI строить дерево.

2019-11-13 09:16 UTC, zykindmitry commented on DevFactoryZ.CharityCRM/WardCategory.cs
> +                if (item.Equals(wardCategory))
Метод Equals является виртуальным. Поскольку Вы его не переопределяли для данного типа, то будет вызвана базовая реализация Object.Equals, которая в свою очередь может меняться от версии к версии и не гарантирует, что для двух объектов с одним и тем же id, он вернет true. Т.о чтобы пользоваться этим методом его надо переопределить и явно указать критерии сравнения. P.S. еще можно переопределить оператор ==